name: "image"
on:
  push:
    tags:
      - "*"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      # - uses: DeterminateSystems/magic-nix-cache-action@v7
      - run: |
          GITHUB_REPOSITORY="${{ github.repository }}" \
          nix build -f .github/image.nix
      - uses: warjiang/setup-skopeo@v0.1.3
      - run: |
          skopeo copy \
            docker-archive:result \
            docker://${{ env.REGISTRY }}/${{ github.repository }}:latest \
            --dest-creds=${{ github.actor }}:${{ secrets.GH_PAT }}
          skopeo copy \
            docker-archive:result \
            docker://${{ env.REGISTRY }}/${{ github.repository }}:${{ github.ref_name }} \
            --dest-creds=${{ github.actor }}:${{ secrets.GH_PAT }}
